version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/secret123"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
volumes:
  neo4j-data:
  neo4j-logs:
